Mvc5OnlineTicariOtomasyon/Models/Siniflar/Kategori.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Mvc5OnlineTicariOtomasyon.Models.Siniflar
{
    public class Kategori
    {
        [Key]
        public int KategoriID { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string KategoriAd { get; set; }
        public ICollection<Urun> Uruns { get; set; }
    }
}

Mvc5OnlineTicariOtomasyon/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc5OnlineTicariOtomasyon.Models.Siniflar;

namespace Mvc5OnlineTicariOtomasyon.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Kategoris.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult KategoriEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult KategoriEkle(Kategori k)
        {
            c.Kategoris.Add(k);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KategoriSil(int id)
        {
            var ktg = c.Kategoris.Find(id);
            c.Kategoris.Remove(ktg);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KategoriGetir(int id)
        {
            var kategori = c.Kategoris.Find(id);
            return View("KategoriGetir",kategori);
        }

        public ActionResult KategoriGuncelle(Kategori k)
        {
            var ktgr = c.Kategoris.Find(k.KategoriID);
            ktgr.KategoriAd = k.KategoriAd;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Mvc5OnlineTicariOtomasyon/Views/Kategori/Index.cshtml
@using Mvc5OnlineTicariOtomasyon.Models.Siniflar
@model List<Kategori>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>ID</th>
        <th>Kategori Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>

    @foreach (var k in Model)
    {
        <tr>
            <td>
                @k.KategoriID
            </td>
            <td>
                @k.KategoriAd
            </td>
            <td><a href="/Kategori/KategoriSil/@k.KategoriID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Kategori/KategoriGetir/@k.KategoriID" class="btn btn-success">Güncelle</a></td>
        </tr>
    }

</table>

<a href="/Kategori/KategoriEkle" class="btn btn-primary">Yeni Kategori</a>

Mvc5OnlineTicariOtomasyon/Views/Kategori/KategoriEkle.cshtml
@model Mvc5OnlineTicariOtomasyon.Models.Siniflar.Kategori
@{
    ViewBag.Title = "KategoriEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Kategori Sayfası</h2>
<br />

<form class="form-group" method="post">
    @Html.LabelFor(x=>x.KategoriAd)
    @Html.TextBoxFor(x=>x.KategoriAd, new {@class="form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

Mvc5OnlineTicariOtomasyon/Views/Kategori/KategoriGetir.cshtml
@model Mvc5OnlineTicariOtomasyon.Models.Siniflar.Kategori
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Kategori Güncelleme Sayfası</h2>
<br />
@using (Html.BeginForm("KategoriGuncelle", "Kategori", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.KategoriAd)
        @Html.TextBoxFor(x => x.KategoriAd, new {@class="form-control" })
        @Html.HiddenFor(x=>x.KategoriID)
    </div>
    <button class="btn btn-warning">Güncelle</button>
}