Mvc5OnlineTicariOtomasyon/Models/Siniflar/Urun.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Mvc5OnlineTicariOtomasyon.Models.Siniflar
{
    public class Urun
    {
        [Key]
        public int Urunid { get; set; }

        [Column(TypeName ="Varchar")]
        [StringLength(30)]
        public string UrunAd { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string Marka { get; set; }
        public short Stok { get; set; }
        public decimal AlisFiyat { get; set; }
        public decimal SatisFiyat { get; set; }
        public bool Durum { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(250)]
        public string UrunGorsel { get; set; }
        public int Kategoriid { get; set; }
        public virtual Kategori Kategori { get; set; }
        public ICollection<SatisHareket> SatisHarekets { get; set; }
    }
}

Mvc5OnlineTicariOtomasyon/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc5OnlineTicariOtomasyon.Models.Siniflar;

namespace Mvc5OnlineTicariOtomasyon.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        Context c = new Context();
        public ActionResult Index()
        {
            var urunler = c.Uruns.Where(x => x.Durum == true).ToList();
            return View(urunler);
        }

        [HttpGet]
        public ActionResult YeniUrun()
        {
            List<SelectListItem> deger1 = (from x in c.Kategoris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.KategoriAd,
                                               Value = x.KategoriID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            return View();
        }
        [HttpPost]
        public ActionResult YeniUrun(Urun p)
        {
            c.Uruns.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunSil(int id)
        {
            var deger = c.Uruns.Find(id);
            deger.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Kategoris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.KategoriAd,
                                               Value = x.KategoriID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            var urundeger = c.Uruns.Find(id);
            return View("UrunGetir", urundeger);
        }

        public ActionResult UrunGuncelle(Urun p)
        {
            var urn = c.Uruns.Find(p.Urunid);
            urn.AlisFiyat = p.AlisFiyat;
            urn.Durum = p.Durum;
            urn.Kategoriid = p.Kategoriid;
            urn.Marka = p.Marka;
            urn.SatisFiyat = p.SatisFiyat;
            urn.Stok = p.Stok;
            urn.UrunAd = p.UrunAd;
            urn.UrunGorsel = p.UrunGorsel;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunListesi()
        {
            var degerler = c.Uruns.ToList();
            return View(degerler);
        }

    }
}

Mvc5OnlineTicariOtomasyon/Views/Urun/Index.cshtml
@using Mvc5OnlineTicariOtomasyon.Models.Siniflar;
@model List<Urun>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>ÜRÜN</th>
        <th>MARKA</th>
        <th>STOK</th>
        <th>ALIŞ FİYAT</th>
        <th>SATIŞ FİYAT</th>
        <th>KATEGORİ</th>
        <th>GÖRSEL</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>
    @foreach (var u in Model)
    {
        <tr>
            <td>@u.Urunid</td>
            <td>@u.UrunAd</td>
            <td>@u.Marka</td>
            <td>@u.Stok</td>
            <td>@u.AlisFiyat</td>
            <td>@u.SatisFiyat</td>
            <td>@u.Kategori.KategoriAd</td>
            <td>@u.UrunGorsel</td>
            <td>
                <a href="/Urun/UrunSil/@u.Urunid" class="btn btn-danger">Sil</a>
            </td>
            <td>
                <a href="/Urun/UrunGetir/@u.Urunid" class="btn btn-success">Güncelle</a>
            </td>
        </tr>
    }
</table>
<a href="/Urun/YeniUrun/" class="btn btn-info">Yeni Ürün</a>

Mvc5OnlineTicariOtomasyon/Views/Urun/UrunGetir.cshtml
@model Mvc5OnlineTicariOtomasyon.Models.Siniflar.Urun
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Ürün Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("UrunGuncelle", "Urun", FormMethod.Post))
{
    @Html.HiddenFor(x=>x.Urunid)
    @Html.LabelFor(x => x.UrunAd)
    @Html.TextBoxFor(x => x.UrunAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Marka)
    @Html.TextBoxFor(x => x.Marka, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Stok)
    @Html.TextBoxFor(x => x.Stok, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.AlisFiyat)
    @Html.TextBoxFor(x => x.AlisFiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.SatisFiyat)
    @Html.TextBoxFor(x => x.SatisFiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Kategori)
    @Html.DropDownListFor(x => x.Kategoriid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    @*@Html.TextBoxFor(x => x.Kategoriid, new { @class = "form-control" })*@
    <br />
    @Html.LabelFor(x => x.UrunGorsel)
    @Html.TextBoxFor(x => x.UrunGorsel, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Durum)
    @Html.TextBoxFor(x => x.Durum, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>

}

Mvc5OnlineTicariOtomasyon/Views/Urun/UrunListesi.cshtml
@using Mvc5OnlineTicariOtomasyon.Models.Siniflar
@model List<Urun>
@{
    Layout = null;
}

<br />

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Bootstrap 4 Responsive Datatable and Export to PDF, CSV</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">

</head>

<body>

    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">

        <thead>

            <tr>

                <th>Ürün Id</th>

                <th>Adı</th>

                <th>Marka</th>

                <th>Stok</th>

                <th>Alış Fiyat</th>

                <th>Satış Fiyat</th>

                <th>Durum</th>

                <th>Kategori</th>

            </tr>

        </thead>

        <tbody>

            @foreach (var x in Model)

            {

                <tr>

                    <td>@x.Urunid</td>

                    <td>@x.UrunAd</td>

                    <td>@x.Marka</td>

                    <td>@x.Stok</td>

                    <td>@x.AlisFiyat</td>

                    <td>@x.SatisFiyat</td>

                    <td>@x.Durum</td>

                    <td>@x.Kategori.KategoriAd</td>

                </tr>

            }



        </tbody>

    </table>

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>

    <script>

        $(document).ready(function () {

            var table = $('#example').DataTable({

                lengthChange: false,

                buttons: ['copy', 'excel', 'csv', 'pdf', 'colvis']

            });



            table.buttons().container()

                .appendTo('#example_wrapper .col-md-6:eq(0)');

        });

    </script>

</body>

</html>

Mvc5OnlineTicariOtomasyon/Views/Urun/YeniUrun.cshtml
@model Mvc5OnlineTicariOtomasyon.Models.Siniflar.Urun
@{
    ViewBag.Title = "YeniUrun";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yeni Ürün Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.UrunAd)
    @Html.TextBoxFor(x => x.UrunAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Marka)
    @Html.TextBoxFor(x => x.Marka, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Stok)
    @Html.TextBoxFor(x => x.Stok, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.AlisFiyat)
    @Html.TextBoxFor(x => x.AlisFiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.SatisFiyat)
    @Html.TextBoxFor(x => x.SatisFiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Kategori)
    @Html.DropDownListFor(x=>x.Kategoriid,(List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    @*@Html.TextBoxFor(x => x.Kategoriid, new { @class = "form-control" })*@
    <br />
    @Html.LabelFor(x => x.UrunGorsel)
    @Html.TextBoxFor(x => x.UrunGorsel, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Durum)
    @Html.TextBoxFor(x => x.Durum, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Kaydet</button>
</form>