Mvc5OnlineTicariOtomasyon/Models/Siniflar/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Mvc5OnlineTicariOtomasyon.Models.Siniflar
{
    public class Personel
    {
        [Key]
        public int Personelid { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelAd { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelSoyad { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(250)]
        public string PersonelGorsel { get; set; }
        public ICollection<SatisHareket> SatisHarekets { get; set; }
        public int Departmanid { get; set; }
        public virtual Departman Departman { get; set; }
    }
}

Mvc5OnlineTicariOtomasyon/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc5OnlineTicariOtomasyon.Models.Siniflar;

namespace Mvc5OnlineTicariOtomasyon.Controllers
{
    public class PersonelController : Controller
    {
        // GET: Personel
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Personels.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult PersonelEkle()
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.Departmanid.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            return View();
        }

        [HttpPost]
        public ActionResult PersonelEkle(Personel p)
        {
            c.Personels.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonelGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.Departmanid.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            var prs = c.Personels.Find(id);
            return View("PersonelGetir",prs);
        }

        public ActionResult PersonelGuncelle(Personel p)
        {
            var prsn = c.Personels.Find(p.Personelid);
            prsn.PersonelAd = p.PersonelAd;
            prsn.PersonelSoyad = p.PersonelSoyad;
            prsn.PersonelGorsel = p.PersonelGorsel;
            prsn.Departmanid = p.Departmanid;
            c.SaveChanges();
            return RedirectToAction("Index");
            
        }


    }
}

Mvc5OnlineTicariOtomasyon/Views/Personel/Index.cshtml
@using Mvc5OnlineTicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>ID</th>
        <th>Personel Adı</th>
        <th>Personel Soyad</th>
        <th>Görsel</th>
        <th>Departman</th>
        <th>Güncelle</th>
        <th>Satışlar</th>
    </tr>

    @foreach (var k in Model)
    {
        <tr>
            <td>@k.Personelid</td>
            <td>@k.PersonelAd</td>
            <td>@k.PersonelSoyad</td>
            <td>@k.PersonelGorsel</td>
            <td>@k.Departman.DepartmanAd</td>
            <td><a href="/Personel/PersonelGetir/@k.Personelid" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Departman/DepartmanPersonelSatis/@k.Personelid" class="btn btn-default" style="background-color:lightcoral;color:white">Detaylar</a></td>
        </tr>
    }

</table>

<a href="/Personel/PersonelEkle" class="btn btn-info">Yeni Personel</a>

Mvc5OnlineTicariOtomasyon/Views/Personel/PersonelEkle.cshtml
@model Mvc5OnlineTicariOtomasyon.Models.Siniflar.Personel
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Personel Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.PersonelAd)
    @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelSoyad)
    @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelGorsel)
    @Html.TextBoxFor(x => x.PersonelGorsel, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Departman)
    @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    @*@Html.TextBoxFor(x => x.Kategoriid, new { @class = "form-control" })*@
    <br />
    <button class="btn btn-primary">Kaydet</button>
</form>

Mvc5OnlineTicariOtomasyon/Views/Personel/PersonelGetir.cshtml
@model Mvc5OnlineTicariOtomasyon.Models.Siniflar.Personel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Personel Güncelleme Ekranı</h2>
<br />

@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.Personelid)
    @Html.LabelFor(x => x.PersonelAd)
    @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelSoyad)
    @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelGorsel)
    @Html.TextBoxFor(x => x.PersonelGorsel, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Departman)
    @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    <button class="btn btn-default" style="background-color:yellowgreen">Güncelle</button>
</div>
}